#!/usr/bin/env python3
"""Emit the inference-side half of a q3c ablation: DFO iterations x uniform proposal.

`inference_dfo_iterations` and `inference_dfo_num_uniform` refine a control-point
cloud a trained generator already produced. They change nothing about training,
so sweeping them by TRAINING a checkpoint per value would multiply an ablation
by 10 for no new weights. This re-scores every checkpoint the training batch
produced at each inference setting instead — eval cost only.

Reads trials.jsonl (which lives in the repo, so this runs on the laptop) and
writes a batch to submit where the checkpoints are. It never touches one.

    uv run python scripts/make_ablation_reeval.py --active-env pushing \\
        --extra pushing --out batches/ablPushingStatesEval.txt
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--active-env", required=True)
    ap.add_argument("--script", default="combinedv2_cpascounter_training.py")
    ap.add_argument("--extra", default="")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--dfo-iters", type=int, nargs="+", default=[0, 3, 5, 10, 20])
    ap.add_argument("--uniform", type=int, nargs="+", default=None,
                    help="inference_dfo_num_uniform values. Default: [0] for the "
                         "pixel envs, [0, 8] for pushing states (the "
                         "'inference_uniform_proposal false/true' axis).")
    ap.add_argument("--min-trial-id", type=int, default=0,
                    help="only re-score trials at or above this id, so an "
                         "ablation batch is not mixed with older checkpoints")
    ap.add_argument("--per-line", type=int, default=6)
    args = ap.parse_args()

    uniform = args.uniform
    if uniform is None:
        uniform = [0, 8] if args.active_env == "pushing" else [0]

    import hyperparam_search as hs
    path = hs._trials_path(args.script, active_env=args.active_env)
    if not path.exists():
        raise SystemExit(f"no trials at {path}")

    # Training runs only: a checkpoint_dir seen for the first time. Later rows on
    # the same dir are themselves re-scores and must not be re-scored again.
    seen, todo = set(), []
    for line in open(path):
        if not line.strip():
            continue
        r = json.loads(line)
        if not r.get("num_seeds"):
            continue
        cd = r.get("checkpoint_dir")
        if cd in seen:
            continue
        seen.add(cd)
        if int(r.get("trial_id", -1)) >= args.min_trial_id:
            todo.append(r["trial_id"])
    if not todo:
        raise SystemExit(f"no training runs at or above trial id {args.min_trial_id}")

    ex = f"--extra {args.extra} " if args.extra else ""
    grid = [(d, u) for d in args.dfo_iters for u in uniform]
    lines = [
        f"# {args.active_env} — inference-side ablation for the q3c sweep.\n"
        f"#\n"
        f"# EVAL ONLY. Re-scores {len(todo)} trained checkpoints at every\n"
        f"# (inference_dfo_iterations, inference_dfo_num_uniform) combination:\n"
        f"#   dfo iterations      {args.dfo_iters}\n"
        f"#   uniform proposal    {uniform}"
        + ("   (false -> 0, true -> 8)\n" if len(uniform) > 1 else "\n")
        + f"#\n"
        f"# {len(grid)} settings x {len(todo)} checkpoints. Note the uniform count\n"
        f"# only does anything when the DFO loop runs: at 0 iterations there is no\n"
        f"# population to add uniform samples to, so those rows are duplicates by\n"
        f"# construction and are emitted once.\n"
        f"#\n"
        f"# Generated by scripts/make_ablation_reeval.py from\n"
        f"# {path.relative_to(ROOT)} (trials >= {args.min_trial_id}).\n\n"
    ]
    emitted = set()
    for dfo, unif in grid:
        key = (dfo, unif if dfo > 0 else 0)
        if key in emitted:
            continue
        emitted.add(key)
        ov = {"inference_dfo_iterations": dfo}
        if dfo > 0:
            ov["inference_dfo_num_uniform"] = unif
        for i in range(0, len(todo), args.per_line):
            chunk = todo[i:i + args.per_line]
            lines.append(
                f"uv run --managed-python {ex}python scripts/reeval_trials.py "
                f"--script {args.script} --active-env {args.active_env} "
                f"--trials {' '.join(str(t) for t in chunk)} "
                f"--param-overrides '{json.dumps(ov, separators=(',', ':'))}'\n")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(lines))
    n = sum(1 for x in lines if x.startswith("uv run"))
    print(f"{args.out}: {len(emitted)} settings x {len(todo)} checkpoints -> {n} jobs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
