#!/usr/bin/env python3
"""Emit a cloud=1 re-scoring batch for every dpq3c trial in an environment.

Re-scoring 18 checkpoints showed that ranking the candidate cloud is
neutral-to-harmful, and that dpq3c with the critic switched off is the best
configuration we have. So every new dpq3c run needs its cloud=1 number as a
control, and that control is an EVAL-ONLY re-score of a checkpoint.

This reads trials.jsonl (which lives in the repo, so it runs on the laptop) and
writes a batch file to submit where the checkpoints are. It never touches a
checkpoint itself.

    uv run python scripts/make_cloud1_batch.py --active-env pen --extra "" \
        --out batches/penCLOUD1.txt
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--active-env", required=True)
    ap.add_argument("--script", default="dpq3c_training.py")
    ap.add_argument("--extra", default="",
                    help="uv extra for this env, e.g. libero or pushing. Empty for none.")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--per-line", type=int, default=5,
                    help="trials per reeval command (they share one job)")
    ap.add_argument("--only-unscored-at-1", action="store_true", default=True,
                    help="skip trials that already have a cloud=1 record")
    args = ap.parse_args()

    import hyperparam_search as hs
    path = hs._trials_path(args.script, active_env=args.active_env)
    if not path.exists():
        raise SystemExit(f"no trials at {path}")
    rows = [json.loads(l) for l in open(path) if l.strip()]

    # A trial is a TRAINING run if its checkpoint_dir appears for the first
    # time; later rows on the same dir are re-scores. Only training runs need a
    # cloud=1 control, and only if they do not already have one.
    seen, order, done = {}, [], set()
    for r in rows:
        if not r.get("num_seeds"):
            continue
        cd = r.get("checkpoint_dir")
        if cd not in seen:
            seen[cd] = r["trial_id"]; order.append(r["trial_id"])
        elif (r.get("params") or {}).get("inference_control_points") == 1:
            done.add(seen[cd])
    todo = [t for t in order if not (args.only_unscored_at_1 and t in done)]
    if not todo:
        print("every training run already has a cloud=1 score; nothing to do")
        return 0

    ex = f"--extra {args.extra} " if args.extra else ""
    lines = [
        f"# {args.active_env} — cloud=1 controls for dpq3c (EVAL ONLY, no training).\n"
        f"#\n"
        f"# A cloud of one leaves the critic nothing to rank, so this measures the\n"
        f"# diffusion actor alone. Across both pixel environments that number matched\n"
        f"# or beat the full-cloud one (0.834 vs 0.819 paired, better on 12 of 18),\n"
        f"# and the best result in the project is dpq3c with the critic off. Treat it\n"
        f"# as the primary number, not the control.\n"
        f"#\n"
        f"# Generated by scripts/make_cloud1_batch.py from\n"
        f"# {path.relative_to(ROOT)} — {len(todo)} training runs still need one\n"
        f"# ({len(done)} already scored at cloud=1).\n\n"
    ]
    for i in range(0, len(todo), args.per_line):
        chunk = todo[i:i + args.per_line]
        lines.append(
            f"uv run --managed-python {ex}python scripts/reeval_trials.py "
            f"--script {args.script} --active-env {args.active_env} "
            f"--trials {' '.join(str(t) for t in chunk)} "
            f"--param-overrides '{json.dumps({'inference_control_points': 1}, separators=(',', ':'))}'\n")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(lines))
    print(f"{args.out}: {len(todo)} trials over "
          f"{(len(todo) + args.per_line - 1)//args.per_line} jobs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
